name: Auto Liker

on:
  workflow_dispatch:
    inputs:
      proxy:
        description: 'Enter HTTP proxy:port'
        required: true
      react:
        type: choice
        description: 'Select any React'
        required: true
        default: 'LIKE'
        options: ['LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY']
      post_id:
        description: 'Enter a Post ID'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py
      run: python main.py ${{ github.event.inputs.proxy }} ${{ github.event.inputs.react }} ${{ github.event.inputs.post_id }} "${{ secrets.B64_COOKIE_1 }}" "${{ secrets.B64_COOKIE_2 }}"
      shell: cmd
